version: 2
workflows:
  version: 2
  test-and-build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish-nexus:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/

jobs:
  build:
    docker:
      - image: coco/dropwizardbase-internal:v1.0.3
    steps:
      - checkout
      - run:
          name: Maven
          command: mvn clean verify
  publish-nexus:
    docker:
      - image: coco/dropwizardbase-internal:v1.0.3
    steps:
      - run:
          name: Publish Tag to Nexus repository
          command: |
            mvn versions:set -DnewVersion=${CIRCLE_TAG}
            mvn versions:commit
            mvn deploy
