version: 2
workflows:
  version: 2
  test-and-build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish-nexus:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/

jobs:
  build:
    docker:
      - image: coco/dropwizardbase-internal:v1.0.3
    steps:
      - checkout
      - run:
          name: Maven
          command: mvn clean verify
  publish-nexus:
    docker:
      - image: coco/dropwizardbase-internal:v1.0.3
    steps:
      - run:
          name: Publish Tag to Nexus repository
          command: |
            HASH=$(git log -1 --pretty=format:%H)
            TAG=$(git tag -l --points-at $HASH | head -n1)
            VERSION=${TAG:-untagged}
            mvn versions:set -DnewVersion=$VERSION
            mvn deploy
